# Generated by Django 3.2.22 on 2024-04-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_auto_20210405_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='api_id',
            new_name='name',
        ),
    ]
